[project]
name = "drone-notify"
version = "1.3"
dependencies = [
  "aiohttp>=3.8"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
fast = true
line-length = 100

[tool.pylint.'messages control']
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
]

[tool.mypy]
strict = true
