[project]
name = "drone-notify"
version = "1.3"
dependencies = [
  "bottle==0.12.25",
  "certifi==2023.7.22",
  "chardet==5.2.0",
  "idna==3.4",
  "requests==2.31.0",
  "urllib3==2.0.7",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
fast = true
line-length = 100

[tool.pylint.'messages control']
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
]

[tool.mypy]
strict = true
